{% set name = "urdfdom" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3c780132d9a0331eb2116ea5dac6fa53ad2af86cb09f37258c34febf526d52b4

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('urdfdom', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - console_bridge
    - tinyxml
    - urdfdom_headers
  run:
    - console_bridge
    - tinyxml
    - urdfdom_headers

test:
  requires:
    - pkg-config  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  files:
    - test
  commands:
    - pkg-config --modversion {{ name }}  # [unix]
    - test -f $PREFIX/lib/lib{{ name }}_model${SHLIB_EXT}  # [unix]
    - if exist %PREFIX%\\Library\\CMake\\urdfdom-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/ros/urdfdom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: URDF parser
  dev_url: https://github.com/ros/urdfdom

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
    - seanyen
