{% set name = "urdfdom" %}
{% set version = "2.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 0c4fdcd38558339c18fc44fc26a5cbb735165f09b55a038643a7d338abc06adf
  patches:
    - remove_vendor.patch
    - fix_cmake_config.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('urdfdom', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - console_bridge
    - tinyxml
    - urdfdom_headers
  run:
    - console_bridge
    - tinyxml
    - urdfdom_headers

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - pkg-config --modversion {{ name }}  # [unix]
    - test -f $PREFIX/lib/lib{{ name }}_model${SHLIB_EXT}  # [unix]
    - if exist %PREFIX%\\Library\\CMake\\urdfdom-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/ros/urdfdom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: URDF parser
  dev_url: https://github.com/ros/urdfdom

extra:
  recipe-maintainers:
    - traversaro
    - jcarpent
    - wolfv
    - lesteve
    - seanyen
