{% set name = "urdfdom" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros2/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 241f4e043499a5a674adcb142ca52a63aa9e7ec33721ab4f56892cf08d68633c
  patches:
    - remove_vendor.patch

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('urdfdom', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - console_bridge
    - tinyxml
    - urdfdom_headers
  run:
    - console_bridge
    - tinyxml
    - urdfdom_headers

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - pkg-config --modversion {{ name }}  # [unix]
    - test -f $PREFIX/lib/lib{{ name }}_model${SHLIB_EXT}  # [unix]
    - if exist %PREFIX%\\Library\\CMake\\urdfdom-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/ros2/urdfdom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: URDF parser
  dev_url: https://github.com/ros2/urdfdom

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
    - seanyen
