{% set name = "urdfdom" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1072b2a304295eb299ed70d99914eb2fbf8843c3257e5e51defc5dd457ee6211
  patches:
    - 169.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('urdfdom', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - console_bridge
    - tinyxml
    - urdfdom_headers
  run:
    - console_bridge
    - tinyxml
    - urdfdom_headers

test:
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  files:
    - test
  commands:
    - pkg-config --modversion {{ name }}
    - pkg-config --exists --print-errors --debug {{ name }}
    - pkg-config --validate --print-errors --debug {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}_model${SHLIB_EXT}  # [unix]
    - if exist %PREFIX%\\Library\\CMake\\urdfdom-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/ros/urdfdom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: URDF parser
  dev_url: https://github.com/ros/urdfdom

extra:
  recipe-maintainers:
    - traversaro
    - jcarpent
    - wolfv
    - lesteve
    - seanyen
